import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    home: 'Home',
    products: 'Products',
    about: 'About',
    contact: 'Contact',
    
    // Hero Section
    heroTitle: 'Leading Metal & Electrical Solutions Provider',
    heroSubtitle: 'Premium quality transformers, cables, and metal products for all your electrical needs',
    getQuote: 'Get Quote',
    viewProducts: 'View Products',
    
    // Products Section
    ourProducts: 'Our Products',
    productsTitle: 'Our Products',
    productsSubtitle: 'Comprehensive range of electrical and metal products',
    viewAll: 'View All Products',
    availableNow: 'Available Now',
    tapToExpand: 'Tap to Expand',
    tapToCollapse: 'Tap to Collapse',
    productDetails: 'Product Details',
    features: 'Features',
    specifications: 'Specifications',
    
    // About Section
    aboutTitle: 'About Rama Krishna Metal',
    aboutDescription: 'With years of expertise in the electrical and metal industry, we provide top-quality products and services to meet all your industrial needs. Our commitment to excellence and customer satisfaction makes us your trusted partner.',
    
    // About Features
    premiumQuality: 'Premium Quality',
    premiumQualityDesc: 'Premium Quality Products',
    reliableProducts: 'Reliable Products',
    reliableProductsDesc: 'Reliable Products Description',
    fastDelivery: 'Fast Delivery',
    fastDeliveryDesc: 'Fast Delivery Description',
    excellentService: 'Excellent Service',
    excellentServiceDesc: 'Excellent Service Description',
    
    // Why Choose Us
    whyChooseUs: 'Why Choose Us',
    premiumMaterials: 'Premium Materials',
    premiumMaterialsDesc: 'Premium Materials Description',
    expertTeam: 'Expert Team',
    expertTeamDesc: 'Expert Team Description',
    competitivePricing: 'Competitive Pricing',
    competitivePricingDesc: 'Competitive Pricing Description',
    customerFocus: 'Customer Focus',
    customerFocusDesc: 'Customer Focus Description',
    
    // Contact Section
    contactTitle: 'Get In Touch',
    getInTouch: 'Get In Touch',
    sendMessage: 'Send Us a Message',
    name: 'Name',
    yourName: 'Your Name',
    phone: '+91 8319066874',
    yourPhone: 'Your Phone',
    email: 'rkmetalbhopal@gmail.com',
    yourEmail: 'Your Email',
    subject: 'Subject',
    message: 'Message',
    yourMessage: 'Your Message',
    sendMessageBtn: 'Send Message',
    sending: 'Sending...',
    callNow: 'Call Now',
    emailUs: 'Email Us',
    address: 'Industrial Area, Govindpura, Bhopal, M.P. 462023',
    businessHours: 'Business Hours',
    businessHoursTime: 'Mon - Sat: 9:00 AM - 6:00 PM',
    
    // Footer
    footerDescription: 'Your trusted partner for all electrical and metal product needs.',
    quickLinks: 'Quick Links',
    followUs: 'Follow Us',
    allRightsReserved: 'All rights reserved.',
    
    // Floating cards
    isoCertified: 'ISO Certified',
    support247: '24/7 Support',

    // Product specific translations
    powerTransformerTank: 'Power Transformer Tank',
    powerTransformerTankDesc: 'High-quality power transformer tanks designed for durability and optimal performance in electrical power systems',
    distributionTransformerTanks: 'Distribution Transformer Tanks',
    distributionTransformerTanksDesc: 'Robust distribution transformer tanks engineered for reliable power distribution networks',
    vcross: 'V Cross Arms',
    vcrossDesc: 'High-quality V cross arms for electrical transmission lines',
    transformer: 'Distribution Transformers',
    transformerDesc: 'Reliable distribution transformers for power distribution',
    transformerOil: 'Transformer Oil',
    transformerOilDesc: 'Premium quality transformer oil for optimal performance',
    earthingPipeChannel: 'Earthing Pipe & Channel',
    earthingPipeChannelDesc: 'Earthing solutions for electrical safety',
    aluminumSuperDPCWire: 'Aluminum Super/DPC Wire',
    aluminumSuperDPCWireDesc: 'High-grade aluminum wires for electrical applications',
    copperSuperDPCWire: 'Copper Super/DPC Wire',
    copperSuperDPCWireDesc: 'Premium copper wires for superior conductivity',
    allTypesCablesLugs: 'All Types Cables & Lugs',
    allTypesCablesLugsDesc: 'Complete range of cables and lugs for electrical connections',
    conductorWire: 'Conductor Wire',
    conductorWireDesc: 'High-quality conductor wires for electrical transmission',
    giWire: 'GI Wire',
    giWireDesc: 'Galvanized iron wire for various electrical applications',
    transformer200KVA: '200 KVA Transformer',
    transformer200KVADesc: '200 KVA capacity transformer for medium-scale applications',
    transformer100KVA: '100 KVA Transformer',
    transformer100KVADesc: '100 KVA capacity transformer for small to medium applications',
    distributionTransformer: 'Distribution Transformer',
    distributionTransformerDesc: 'Efficient distribution transformers for power networks',
    transformerTank: 'Transformer Tank',
    transformerTankDesc: 'Robust transformer tanks for housing electrical components',

    highVoltageRating: 'High voltage rating for transmission lines',
    weatherResistant: 'Weather resistant coating and materials',
    easyInstallation: 'Easy installation and maintenance',
    longLifespan: 'Long lifespan with minimal degradation',
    energyEfficient: 'Energy efficient operation',
    lowNoiseoperation: 'Low noise operation',
    compactDesign: 'Compact design for space optimization',
    advancedCooling: 'Advanced cooling system',
    qualityTested: 'Quality tested and certified',
    highDielectricStrength: 'High dielectric strength',
    lowViscosity: 'Low viscosity for better flow',
    thermalStability: 'Excellent thermal stability',
    moistureResistant: 'Moisture resistant formulation',
    ecofriendly: 'Eco-friendly and biodegradable',
    corrosionResistant: 'Corrosion resistant materials',
    lowResistance: 'Low electrical resistance',
    easyMaintenance: 'Easy maintenance and replacement',
    durableConstruction: 'Durable construction for longevity',
    standardCompliant: 'Compliant with industry standards',
    lightWeight: 'Lightweight design for easy handling',
    highConductivity: 'High electrical conductivity',
    flexibleDesign: 'Flexible design for various applications',
    costEffective: 'Cost-effective solution',
    industrialGrade: 'Industrial grade quality',
    superiorConductivity: 'Superior electrical conductivity',
    antiCorrosion: 'Anti-corrosion properties',
    highTensileStrength: 'High tensile strength',
    longDurable: 'Long-lasting and durable',
    precisionEngineered: 'Precision engineered components',
    multiSizeCompatible: 'Compatible with multiple sizes',
    easyConnection: 'Easy connection and installation',
    reliableContact: 'Reliable electrical contact',
    industrialStandard: 'Meets industrial standards',
    highPurity: 'High purity copper/aluminum',
    flexibleStranding: 'Flexible stranding design',
    temperatureResistant: 'Temperature resistant insulation',
    optimalPerformance: 'Optimal electrical performance',
    galvanizedCoating: 'Galvanized protective coating',
    rustProof: 'Rust-proof and corrosion resistant',
    uniformThickness: 'Uniform coating thickness',
    longLasting: 'Long-lasting protection',
    robustConstruction: 'Robust and durable construction',
    leakProof: 'Leak-proof design and sealing',
    thermalManagement: 'Advanced thermal management',
    easyAccess: 'Easy access for maintenance',

    '11kv33kvRating': '11kV to 33kV voltage rating',
    hotDipGalvanized: 'Hot-dip galvanized finish',
    boltedConnection: 'Bolted connection system',
    is2713Standard: 'IS 2713 standard compliance',
    customizable: 'Customizable dimensions available',
    singleThreePhase: 'Single and three-phase options',
    oilAirCooled: 'Oil and air cooling systems',
    tapChanger: 'On-load tap changer facility',
    vectorGroup: 'Various vector group configurations',
    protectionClass: 'IP rating protection class',
    breakdownVoltage: 'High breakdown voltage capacity',
    specificGravity: 'Optimal specific gravity range',
    flashPoint: 'High flash point temperature',
    pourPoint: 'Low pour point for cold climates',
    moistureContent: 'Low moisture content specification',
    copperBonded: 'Copper bonded steel construction',
    variousLengths: 'Available in various lengths',
    threadedConnections: 'Threaded connection options',
    earthingCompound: 'Earthing enhancement compound',
    testCertificate: 'Test certificate provided',
    aacsConductor: 'AACS conductor specification',
    pvcInsulation: 'PVC insulation material',
    flexibleStrands: 'Multiple flexible strands',
    ampereRating: 'Current carrying capacity rating',
    bsStandard: 'BS standard compliance',
    copperConductor: 'Pure copper conductor',
    superiorInsulation: 'Superior grade insulation',
    multiCore: 'Multi-core configuration',
    ampacityRating: 'High ampacity rating',
    ieeeStandard: 'IEEE standard compliance',
    aluminumCopper: 'Aluminum and copper options',
    compressionType: 'Compression type connections',
    boltedDesign: 'Bolted design for reliability',
    multipleRanges: 'Multiple size ranges',
    contactResistance: 'Low contact resistance',
    strandsConfig: 'Optimized strands configuration',
    conductorSize: 'Various conductor sizes',
    currentRating: 'Current carrying rating',
    voltageGrade: 'Voltage grade specification',
    flexibilityTest: 'Flexibility test certified',
    zincCoating: 'Zinc coating specification',
    wireGauge: 'Standard wire gauge sizes',
    tensileTest: 'Tensile strength tested',
    uniformCoating: 'Uniform coating thickness',
    astmStandard: 'ASTM standard compliance',
    mildSteelConstruction: 'Mild steel construction',
    paintFinish: 'Protective paint finish',
    gasketSealing: 'Gasket sealing system',
    drainValve: 'Drain valve facility',
    testPressure: 'Test pressure rating',

    // Generic specifications
    variousSizes: 'Available in various sizes',
    customSolutions: 'Custom solutions available',
    wholesaleRetail: 'Wholesale and retail options',
    fastProcessing: 'Fast order processing',
    qualityCertified: 'Quality certified products',
    highQualityMaterials: 'High-quality raw materials',
    industryStandards: 'Meets industry standards',
    reliablePerformance: 'Reliable performance guaranteed',
    quickDelivery: 'Quick delivery service',
    technicalSupport: '24/7 technical support'
  },
  hi: {
    // Navigation
    home: 'होम',
    products: 'उत्पाद',
    about: 'के बारे में',
    contact: 'संपर्क',
    
    // Hero Section - Fixed overflow
    heroTitle: 'अग्रणी धातु और विद्युत समाधान प्रदाता',
    heroSubtitle: 'आपकी सभी विद्युत आवश्यकताओं के लिए प्रीमियम गुणवत्ता ट्रांसफार्मर, केबल और धातु उत्पाद',
    getQuote: 'कोटेशन पाएं',
    viewProducts: 'उत्पाद देखें',
    
    // Products Section
    ourProducts: 'हमारे उत्पाद',
    productsTitle: 'हमारे उत्पाद',
    productsSubtitle: 'विद्युत और धातु उत्पादों की व्यापक श्रृंखला',
    viewAll: 'सभी उत्पाद देखें',
    availableNow: 'अभी उपलब्ध',
    tapToExpand: 'विस्तार के लिए टैप करें',
    tapToCollapse: 'संक्षिप्त करने के लिए टैप करें',
    productDetails: 'उत्पाद विवरण',
    features: 'विशेषताएं',
    specifications: 'विनिर्देश',
    
    // About Section
    aboutTitle: 'राम कृष्णा मेटल के बारे में',
    aboutDescription: 'विद्युत और धातु उद्योग में वर्षों की विशेषज्ञता के साथ, हम आपकी सभी औद्योगिक आवश्यकताओं को पूरा करने के लिए उच्च गुणवत्ता वाले उत्पाद और सेवाएं प्रदान करते हैं।',
    
    // About Features  
    premiumQuality: 'प्रीमियम गुणवत्ता',
    premiumQualityDesc: 'उच्चतम गुणवत्ता वाले उत्पाद',
    reliableProducts: 'विश्वसनीय उत्पाद',
    reliableProductsDesc: 'भरोसेमंद और टिकाऊ उत्पाद',
    fastDelivery: 'तेज़ डिलीवरी',
    fastDeliveryDesc: 'समय पर और तेज़ डिलीवरी सेवा',
    excellentService: 'उत्कृष्ट सेवा',
    excellentServiceDesc: 'बेहतरीन ग्राहक सेवा और सहायता',
    
    // Why Choose Us
    whyChooseUs: 'हमें क्यों चुनें',
    premiumMaterials: 'प्रीमियम सामग्री',
    premiumMaterialsDesc: 'उच्च गुणवत्ता वाली कच्ची सामग्री',
    expertTeam: 'विशेषज्ञ टीम',
    expertTeamDesc: 'अनुभवी और कुशल विशेषज्ञ टीम',
    competitivePricing: 'प्रतिस्पर्धी मूल्य',
    competitivePricingDesc: 'बाजार में सबसे अच्छे दाम',
    customerFocus: 'ग्राहक केंद्रित',
    customerFocusDesc: 'ग्राहक संतुष्टि हमारी प्राथमिकता',
    
    // Contact Section
    contactTitle: 'संपर्क में रहें',
    getInTouch: 'संपर्क करें',
    sendMessage: 'हमें संदेश भेजें',
    name: 'नाम',
    yourName: 'आपका नाम',
    phone: '+91 8319066874',
    yourPhone: 'आपका फ़ोन',
    email: 'rkmetalbhopal@gmail.com',
    yourEmail: 'आपका ईमेल',
    subject: 'विषय',
    message: 'संदेश',
    yourMessage: 'आपका संदेश',
    sendMessageBtn: 'संदेश भेजें',
    sending: 'भेजा जा रहा है...',
    callNow: 'अभी कॉल करें',
    emailUs: 'हमें ईमेल करें',
    address: 'इंडस्ट्रियल एरिया, गोविंदपुरा, भोपाल, म.प्र. 462023',
    businessHours: 'व्यापारिक समय',
    businessHoursTime: 'सोमवार - शनिवार: सुबह 9:00 - शाम 6:00',
    
    // Footer
    footerDescription: 'सभी विद्युत और धातु उत्पाद आवश्यकताओं के लिए आपका विश्वसनीय साझीदार।',
    quickLinks: 'त्वरित लिंक',
    followUs: 'हमें फॉलो करें',
    allRightsReserved: 'सभी अधिकार सुरक्षित।',
    
    // Floating cards
    isoCertified: 'ISO प्रमाणित',
    support247: '24/7 सहायता',

    // Product specific translations - Hindi
    powerTransformerTank: 'पावर ट्रांसफार्मर टैंक',
    powerTransformerTankDesc: 'विद्युत पावर सिस्टम में स्थायित्व और उत्कृष्ट प्रदर्शन के लिए डिज़ाइन किए गए उच्च गुणवत्ता वाले पावर ट्रांसफार्मर टैंक',
    distributionTransformerTanks: 'वितरण ट्रांसफार्मर टैंक',
    distributionTransformerTanksDesc: 'विश्वसनीय पावर वितरण नेटवर्क के लिए इंजीनियर्ड मजबूत वितरण ट्रांसफार्मर टैंक',
    vcross: 'वी क्रॉस आर्म्स',
    vcrossDesc: 'विद्युत ट्रांसमिशन लाइनों के लिए उच्च गुणवत्ता वाले वी क्रॉस आर्म्स',
    transformer: 'वितरण ट्रांसफार्मर',
    transformerDesc: 'विद्युत वितरण के लिए विश्वसनीय वितरण ट्रांसफार्मर',
    transformerOil: 'ट्रांसफार्मर ऑयल',
    transformerOilDesc: 'उत्कृष्ट प्रदर्शन के लिए प्रीमियम गुणवत्ता ट्रांसफार्मर ऑयल',
    earthingPipeChannel: 'अर्थिंग पाइप और चैनल',
    earthingPipeChannelDesc: 'विद्युत सुरक्षा के लिए अर्थिंग समाधान',
    aluminumSuperDPCWire: 'Aluminum Super/DPC Wire',
    aluminumSuperDPCWireDesc: 'High-grade aluminum wires for electrical applications',
    copperSuperDPCWire: 'Copper Super/DPC Wire',
    copperSuperDPCWireDesc: 'Premium copper wires for superior conductivity',
    allTypesCablesLugs: 'सभी प्रकार के केबल और लग्स',
    allTypesCablesLugsDesc: 'विद्युत कनेक्शन के लिए केबल और लग्स की पूरी श्रृंखला',
    conductorWire: 'कंडक्टर वायर',
    conductorWireDesc: 'विद्युत ट्रांसमिशन के लिए उच्च गुणवत्ता कंडक्टर वायर',
    giWire: 'जीआई वायर',
    giWireDesc: 'विभिन्न विद्युत अनुप्रयोगों के लिए गैल्वनाइज़्ड आयरन वायर',
    transformer200KVA: '200 केवीए ट्रांसफार्मर',
    transformer200KVADesc: 'मध्यम स्तरीय अनुप्रयोगों के लिए 200 केवीए क्षमता ट्रांसफार्मर',
    transformer100KVA: '100 केवीए ट्रांसफार्मर',
    transformer100KVADesc: 'छोटे से मध्यम अनुप्रयोगों के लिए 100 केवीए क्षमता ट्रांसफार्मर',
    distributionTransformer: 'वितरण ट्रांसफार्मर',
    distributionTransformerDesc: 'विद्युत नेटवर्क के लिए कुशल वितरण ट्रांसफार्मर',
    transformerTank: 'ट्रांसफार्मर टैंक',
    transformerTankDesc: 'विद्युत घटकों को रखने के लिए मजबूत ट्रांसफार्मर टैंक',

    highVoltageRating: 'ट्रांसमिशन लाइनों के लिए उच्च वोल्टेज रेटिंग',
    weatherResistant: 'मौसम प्रतिरोधी कोटिंग और सामग्री',
    easyInstallation: 'आसान स्थापना और रखरखाव',
    longLifespan: 'न्यूनतम क्षरण के साथ लंबी जीवनकाल',
    energyEfficient: 'ऊर्जा कुशल संचालन',
    lowNoiseoperation: 'कम शोर संचालन',
    compactDesign: 'स्थान अनुकूलन के लिए कॉम्पैक्ट डिज़ाइन',
    advancedCooling: 'उन्नत शीतलन प्रणाली',
    qualityTested: 'गुणवत्ता परीक्षणित और प्रमाणित',
    highDielectricStrength: 'उच्च डाइइलेक्ट्रिक शक्ति',
    lowViscosity: 'बेहतर प्रवाह के लिए कम चिपचिपाहट',
    thermalStability: 'उत्कृष्ट थर्मल स्थिरता',
    moistureResistant: 'नमी प्रतिरोधी फॉर्मूलेशन',
    ecofriendly: 'पर्यावरण अनुकूल और बायो-डिग्रेडेबल',
    corrosionResistant: 'जंग प्रतिरोधी सामग्री',
    lowResistance: 'कम विद्युत प्रतिरोध',
    easyMaintenance: 'आसान रखरखाव और प्रतिस्थापन',
    durableConstruction: 'दीर्घायु के लिए टिकाऊ निर्माण',
    standardCompliant: 'उद्योग मानकों के अनुपालन',
    lightWeight: 'आसान हैंडलिंग के लिए हल्का डिज़ाइन',
    highConductivity: 'उच्च विद्युत चालकता',
    flexibleDesign: 'विभिन्न अनुप्रयोगों के लिए लचीला डिज़ाइन',
    costEffective: 'लागत प्रभावी समाधान',
    industrialGrade: 'औद्योगिक ग्रेड गुणवत्ता',
    superiorConductivity: 'बेहतर विद्युत चालकता',
    antiCorrosion: 'जंग रोधी गुण',
    highTensileStrength: 'उच्च तन्यता शक्ति',
    longDurable: 'लंबे समय तक चलने वाला और टिकाऊ',
    precisionEngineered: 'सटीक इंजीनियर्ड घटक',
    multiSizeCompatible: 'कई साइज़ के साथ संगत',
    easyConnection: 'आसान कनेक्शन और स्थापना',
    reliableContact: 'विश्वसनीय विद्युत संपर्क',
    industrialStandard: 'औद्योगिक मानकों को पूरा करता है',
    highPurity: 'उच्च शुद्धता कॉपर/एल्युमिनियम',
    flexibleStranding: 'लचीला स्ट्रैंडिंग डिज़ाइन',
    temperatureResistant: 'तापमान प्रतिरोधी इन्सुलेशन',
    optimalPerformance: 'इष्टतम विद्युत प्रदर्शन',
    galvanizedCoating: 'गैल्वनाइज़्ड सुरक्षात्मक कोटिंग',
    rustProof: 'जंग रोधी और जंग प्रतिरोधी',
    uniformThickness: 'समान कोटिंग मोटाई',
    longLasting: 'लंबे समय तक चलने वाली सुरक्षा',
    robustConstruction: 'मजबूत और टिकाऊ निर्माण',
    leakProof: 'लीक-प्रूफ डिज़ाइन और सीलिंग',
    thermalManagement: 'उन्नत थर्मल प्रबंधन',
    easyAccess: 'रखरखाव के लिए आसान पहुंच',

    '11kv33kvRating': '11केवी से 33केवी वोल्टेज रेटिंग',
    hotDipGalvanized: 'हॉट-डिप गैल्वनाइज़्ड फिनिश',
    boltedConnection: 'बोल्टेड कनेक्शन सिस्टम',
    is2713Standard: 'IS 2713 मानक अनुपालन',
    customizable: 'अनुकूलन योग्य आयाम उपलब्ध',
    singleThreePhase: 'सिंगल और थ्री-फेज़ विकल्प',
    oilAirCooled: 'तेल और हवा शीतलन प्रणाली',
    tapChanger: 'ऑन-लोड टैप चेंजर सुविधा',
    vectorGroup: 'विभिन्न वेक्टर ग्रुप कॉन्फ़िगरेशन',
    protectionClass: 'IP रेटिंग सुरक्षा वर्ग',
    breakdownVoltage: 'उच्च ब्रेकडाउन वोल्टेज क्षमता',
    specificGravity: 'इष्टतम विशिष्ट गुरुत्वाकर्षण रेंज',
    flashPoint: 'उच्च फ्लैश पॉइंट तापमान',
    pourPoint: 'ठंडी जलवायु के लिए कम पोर पॉइंट',
    moistureContent: 'कम नमी सामग्री विनिर्देश',
    copperBonded: 'कॉपर बंधुआ स्टील निर्माण',
    variousLengths: 'विभिन्न लंबाई में उपलब्ध',
    threadedConnections: 'थ्रेडेड कनेक्शन विकल्प',
    earthingCompound: 'अर्थिंग वृद्धि कंपाउंड',
    testCertificate: 'परीक्षण प्रमाणपत्र प्रदान किया गया',
    aacsConductor: 'AACS कंडक्टर विनिर्देश',
    pvcInsulation: 'PVC इन्सुलेशन सामग्री',
    flexibleStrands: 'कई लचीले स्ट्रैंड्स',
    ampereRating: 'करंट कैर्यिंग कैपेसिटी रेटिंग',
    bsStandard: 'BS मानक अनुपालन',
    copperConductor: 'शुद्ध कॉपर कंडक्टर',
    superiorInsulation: 'बेहतर ग्रेड इन्सुलेशन',
    multiCore: 'मल्टी-कोर कॉन्फ़िगरेशन',
    ampacityRating: 'उच्च एम्पैसिटी रेटिंग',
    ieeeStandard: 'IEEE मानक अनुपालन',
    aluminumCopper: 'एल्युमिनियम और कॉपर विकल्प',
    compressionType: 'कंप्रेशन टाइप कनेक्शन',
    boltedDesign: 'विश्वसनीयता के लिए बोल्टेड डिज़ाइन',
    multipleRanges: 'कई साइज़ रेंज',
    contactResistance: 'कम संपर्क प्रतिरोध',
    strandsConfig: 'अनुकूलित स्ट्रैंड्स कॉन्फ़िगरेशन',
    conductorSize: 'विभिन्न कंडक्टर साइज़',
    currentRating: 'करंट कैर्यिंग रेटिंग',
    voltageGrade: 'वोल्टेज ग्रेड विनिर्देश',
    flexibilityTest: 'लचीलापन परीक्षण प्रमाणित',
    zincCoating: 'जिंक कोटिंग विनिर्देश',
    wireGauge: 'स्टैंडर्ड वायर गेज साइज़',
    tensileTest: 'तन्यता शक्ति परीक्षणित',
    uniformCoating: 'समान जिंक कोटिंग',
    astmStandard: 'ASTM मानक अनुपालन',
    mildSteelConstruction: 'माइल्ड स्टील निर्माण',
    paintFinish: 'सुरक्षात्मक पेंट फिनिश',
    gasketSealing: 'गैस्केट सीलिंग सिस्टम',
    drainValve: 'ड्रेन वाल्व सुविधा',
    testPressure: 'टेस्ट प्रेशर रेटिंग',

    // Generic specifications - Hindi
    variousSizes: 'विभिन्न साइज़ में उपलब्ध',
    customSolutions: 'कस्टम समाधान उपलब्ध',
    wholesaleRetail: 'थोक और खुदरा विकल्प',
    fastProcessing: 'तेज़ ऑर्डर प्रोसेसिंग',
    qualityCertified: 'गुणवत्ता प्रमाणित उत्पाद',
    highQualityMaterials: 'उच्च गुणवत्ता कच्चा माल',
    industryStandards: 'उद्योग मानकों को पूरा करता है',
    reliablePerformance: 'विश्वसनीय प्रदर्शन की गारंटी',
    quickDelivery: 'त्वरित डिलीवरी सेवा',
    technicalSupport: '24/7 तकनीकी सहायता'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'hi' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
